### ISSUE TITLE
uhttpd service not starting after reboot

### ISSUE THREAD

**Issue by Daviteusz** [CodeInvers3/PPPwn_ow#9]
After installing PPPwn_ow using commands (online) from readme, uhttpd service is not starting after reboot.
This means that LuCI and pppwn.html are not accessible, also power led is blinking every 0.5s.

I didn't found anything in logs why uhttpd is not starting,

OpenWrt 23.05-SNAPSHOT, r24111-5332351821

**Comment by CodeInvers3** [comment]
I recommend reinstalling everything again. I have fixed several issues in the script. If you find any issues, you can reply to this message

**Comment by CodeInvers3** [comment]
You can try reinstalling uhttpd, pppoe-common, and pppoe-server. When you uninstall them, delete the files /etc/config/uhttpd, /etc/ppp/chap-secrets, /etc/ppp/pap-secrets, and /etc/ppp/pppoe-server-options, as I've removed the use of uhttpd, and some configuration in this file might be causing issues. Then reinstall uhttpd and install PPPw_ow again.

**Comment by Daviteusz** [comment]
I reinstalled the entire firmware without keeping any data, installed PW, and the problem remains the same. The router has plenty of free RAM and memory. Maybe delaying the start of PW would solve the problem 🤔

**Comment by CodeInvers3** [comment]
You can try editing the file `/etc/init.d/pw`. Look for `START=80`, change it to `START=99`, and see if you notice any changes. You can do this via FTP or console.

Generally, if you choose the autorun option when turning on the router, it will keep the light flashing until it activates GoldHEN. It’s not possible to use luCI from the PS4 browser, but it can be accessed from another device.
Once GoldHEN is activated, wait a few seconds until the PPPoE server starts working, which allows luCI to be used again from the PS4.
When running pppwn, it occupies the network, so it’s not possible to use another network service until it has finished its task.

**Comment by Daviteusz** [comment]
> You can try editing the file `/etc/init.d/pw`. Look for `START=80`, change it to `START=99`, and see if you notice any changes. You can do this via FTP or console.

Delaying the pw service solves the problem. Thanks for your time.
